version: "3.7"

services:
  gradle:
    image: ${TAG_ID:-querydroid_build}
    build:
      context: .
    volumes:
      - gradle-cache:/home/gradle/.gradle
    environment:
      - ORG_GRADLE_PROJECT_sonatypeUsername=${SONATYPE_USERNAME}
      - ORG_GRADLE_PROJECT_sonatypePassword=${SONATYPE_PASSWORD}
      - ORG_GRADLE_PROJECT_signingKey=${SIGNING_KEY}
      - ORG_GRADLE_PROJECT_signingPassword=${SIGNING_PASSWORD}

volumes:
  gradle-cache:
